# _config.yml
remote_theme: pages-themes/cayman@v0.2.0  
title: "Kauthara Yakubu's Portfolio"
description: "Data Analyst, IT Risk Analyst, BI Analyst, Data Scientist and AI Engineer"
baseurl: ""  
plugins:
  - jekyll-remote-theme  
